DROP TABLE IF EXISTS LOCATION;

-- I know there are some coordinates data types, but I do not know how to use them :(
CREATE TABLE LOCATION(
  ID SERIAL PRIMARY KEY,
  CITY TEXT NOT NULL,
  REGION TEXT NOT NULL,
  COUNTRY TEXT NOT NULL,
  LATITUDE TEXT NOT NULL,
  LONGITUDE TEXT NOT NULL
);

GRANT SELECT, INSERT ON LOCATION TO ${user};

INSERT INTO LOCATION (CITY, REGION, COUNTRY, LATITUDE, LONGITUDE) VALUES ('Madrid', 'Madrid', 'Spain', '40°23′N', '3°43′W');
INSERT INTO LOCATION (CITY, REGION, COUNTRY, LATITUDE, LONGITUDE) VALUES ('Laussane', 'Vaud', 'Switzerland', '46°31.19′N', '6°38.01′E');
INSERT INTO LOCATION (CITY, REGION, COUNTRY, LATITUDE, LONGITUDE) VALUES ('Quito', 'Pichincha', 'Ecuador', '00°14′S', '78°31′W');
INSERT INTO LOCATION (CITY, REGION, COUNTRY, LATITUDE, LONGITUDE) VALUES ('Casablanca', 'Casablanca-Settat', 'Morocco', '33°32′N', '7°35′W');

COMMIT;
